# .github/actions/my-composite-action/action.yml
name: My Composite Action
description: This action runs multiple steps
runs:
  using: "composite"
  steps:
    - run: echo "Step 1"
    - run: echo "Step 2"
