apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
    spec:
      containers:
        - name: bill
          image: <<ACR name>>.azurecr.io/productapi
          ports:
          - containerPort: 8080