#This workflow will deploy application in Azure Container App. Every deploy will create new revision.
name: Build and Deploy Azure Container App

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
      - 'src/main/java/com/irfanstore/product/**'
      
  # Allow mannually trigger 
  workflow_dispatch:      

  
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        
      - name: Build Solution
        run: mvn package
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Build and Push image to Azure Contianer Registry
        run:  az acr build --registry ${{ secrets.ACR_NAME }} --image ${{ secrets.APP_NAME }}:${{ github.sha }} .
  Deploy:  
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    
       
      - name: Setup Container App CLI Plugin
        run: az extension add --name containerapp --upgrade
         
      - name: AZ Config Set Extension
        run: az config set extension.use_dynamic_install=yes_without_prompt
         
      - name: Set Container Registry
        run: az containerapp registry set -n ${{ secrets.APP_NAME }} -g ${{ secrets.RESOURCE_GROUP }} --server ${{ secrets.ACR_NAME }}.azurecr.io 
        
      - name: Update Container Image
        run: az containerapp update -n ${{ secrets.APP_NAME }} -g ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.APP_NAME }}:${{ github.sha }} --revision-suffix 'ghsha-' ${{ github.sha }}
        
       
        
       
