name: Deploy IaC

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  # Allow mannually trigger 
  workflow_dispatch:

env:
  RESOURCE_GROUP: "test-irf"
  LOCATION: "australiaeast"
  ACR_NAME: "irfacr"
  CONTAINER_APP_ENVIRONMENT: "productapi-environment-test-irf"
  APP_NAME: "productapi"
jobs:
   Deploy:
     runs-on: ubuntu-latest

     steps:
       - name: 'Login via Azure CLI'
         uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
           
       - name: Create Resouse Group  
         run: az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}
       
       - name: Create Azure Container Registry
         run: az acr create --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.ACR_NAME }} --sku Basic --admin-enabled true
         
       - name: Setup Container App CLI Plugin
         run: az extension add --name containerapp --upgrade
       
       - name: Create Container App Environment
         run: az containerapp env create --name ${{ env.CONTAINER_APP_ENVIRONMENT }} --resource-group ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}
         
       - name: Create Container App with Hello World container
         run: az containerapp create --name ${{ env.APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --environment ${{ env.CONTAINER_APP_ENVIRONMENT }} --image mcr.microsoft.com/azuredocs/containerapps-helloworld:latest --target-port 8080 --ingress 'external' 
         
  
         
