#This workflow will deploy Azure Container App Resources
name: Deploy Azure Container App IaC

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  # Allow mannually trigger 
  workflow_dispatch:


jobs:
   Deploy:
     runs-on: ubuntu-latest

     steps:
       - name: 'Login via Azure CLI'
         uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
         
#        - name: Setup Container App CLI Plugin
#          run: az extension add --name containerapp --upgrade

#        - name: AZ Config Set Extension
#          run: az config set extension.use_dynamic_install=yes_without_prompt
        
       - name: Create Resource Group  
         run: az group create --name ${{ secrets.RESOURCE_GROUP }} --location ${{ secrets.LOCATION }}
       
       - name: Create Azure Container Registry
         run: az acr create --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.ACR_NAME }} --sku Basic --admin-enabled true
              
#        - name: Create Container App Environment
#          run: az containerapp env create --name ${{ secrets.CONTAINER_APP_ENVIRONMENT }} --resource-group ${{secrets.RESOURCE_GROUP }} --location ${{ secrets.LOCATION }}
         
#        - name: Wait for Container App Environment to setup
#          run: sleep 4m
         
#        - name: Create Container App with nginx container
#          run: az containerapp create --name ${{ secrets.APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --environment ${{ secrets.CONTAINER_APP_ENVIRONMENT }} --image nginx --target-port 8080 --ingress 'external' --revisions-mode 'multiple'
         
#        - name: Set Container Registry
#          run: az containerapp registry set -n ${{ secrets.APP_NAME }} -g ${{ secrets.RESOURCE_GROUP }} --server ${{ secrets.ACR_NAME }}.azurecr.io 

         
